TRAINING:
  Network: 'MLP'
  EPOCH: 150
  LR: 0.001
  GPU: true
  BATCH: 10
  # K_fold: 5
  VAL_AFTER_EVERY: 1
  TRAIN_DIR: './csv_data/training/independent_mean.csv'       # path to training data
  # VAL_DIR: './csv_data/training/val.csv' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images

